version: '3.9'

services:
  configstore:
    ports:
        - 8000:80
        - 8001:443
    container_name: configstore
    restart: on-failure
    hostname: ConfigStore
    build:
      context: .
      dockerfile: src/FXbox.Cloud/FXbox.Cloud.Server.ConfigStore/Dockerfile
  dashboard:
    ports:
        - 8002:80
    container_name: dashboard
    restart: on-failure
    hostname: Dashboard
    build:
      context: .
      dockerfile: src/FXbox.Cloud/FXbox.Cloud.Client.Dashboard/Dockerfile
  agenthub:
    ports:
        - 8003:80
        - 8004:443
    container_name: agenthub
    restart: on-failure
    hostname: AgentHub
    build:
      context: .
      dockerfile: src/FXbox.Cloud/FXbox.Cloud.Server.AgentHub/Dockerfile
  agenthubdashboard:
    ports:
        - 8005:80
    container_name: agenthubdashboard
    restart: on-failure
    hostname: AgentHubDashboard
    build:
      context: .
      dockerfile: src/FXbox.Cloud/FXbox.Cloud.Client.AgentActivity/Dockerfile
