version: '3.9'

services:

  mongodb:
    image: mongo:3.6
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=hello
    volumes:
      - ./mongo-init/:/docker-entrypoint-initdb.d/:ro
    ports:
      - 27017:27017
      - 9229:9229

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8111:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=hello

  presentation.dashboard:
      ports:
          - 8001:80
      container_name: presentation.dashboard
      build:
        context: .
        dockerfile: src/Cloud/Presentation/FXbox.Cloud.Presentation.Dashboard/Dockerfile
  
  presentation.agents:
      ports:
          - 8002:80
      container_name: presentation.agents
      build:
        context: .
        dockerfile: src/Cloud/Presentation/FXbox.Cloud.Presentation.Agents/Dockerfile
  
  gateway.agent:
    ports:
        - 8003:80
        - 8004:443
    container_name: gateway.agent
    build:
      context: .
      dockerfile: src/Cloud/Gateway/FXbox.Cloud.Gateway.Agent/Dockerfile
  
  gateway.dashboard:
    ports:
        - 8005:80
        - 8006:443
    container_name: gateway.dashboard
    build:
      context: .
      dockerfile: src/Cloud/Gateway/FXbox.Cloud.Gateway.Dashboard/Dockerfile

  services.agents:
    ports:
        - 8007:80
        - 8008:443
    container_name: services.agents
    build:
      context: .
      dockerfile: src/Cloud/Services/FXbox.Cloud.Services.Agents/Dockerfile

  services.configuration:
    ports:
        - 8009:80
        - 8010:443
    container_name: services.configuration
    build:
      context: .
      dockerfile: src/Cloud/Services/FXbox.Cloud.Services.Configuration/Dockerfile

  services.identity:
    ports:
        - 8011:80
        - 8012:443
    container_name: services.identity
    build:
      context: .
      dockerfile: src/Cloud/Services/FXbox.Cloud.Services.Identity/Dockerfile

